ignore:
  - "src/plotters/makie.jl
  - "src/plotters/plots.jl
  - "src/plotters/multiscene.jl
  - "src/plotters/vtkview.jl
  - "src/plotters/meshcat.jl

  # - "path/to/folder"  # ignore folders and all its contents
  # - "test_*.rb"       # wildcards accepted
  # - "**/*.jl"   
